Refactor

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -25,94 +25,110 @@ jobs:
     # - name: Show installed packages
     #   run: dpkg -l
 
-    - name: Aggressive cleanup
+    - name: Free disk space
+      # Free disk space by removing some large directories that we don't use (#15171)
+      # see https://dev.to/mathio/squeezing-disk-space-from-github-actions-runners-an-engineers-guide-3pjg
       run: |
-        echo "Before cleanup, disk usage is:"
-        df -h
-
-        # Remove Android SDKs (frees 12 GB)
-        # sudo du -h -s /usr/local/lib/android
+        # Remove Android SDKs (frees 12 GB on Ubuntu 24.04)
         sudo rm -rf /usr/local/lib/android
-        echo "After removing Android SDKs, disk usage is:"
-        df -h
 
         # Remove Haskell (GHC) (frees 6.4 GB)
-        # sudo du -h -s /usr/local/.ghcup
         sudo rm -rf /usr/local/.ghcup
-        echo "After removing Haskell (GHC), disk usage is:"
-        df -h
 
         # Remove CodeQL and other toolcaches (frees 5.8 GB)
-        # sudo du -h -s /opt/hostedtoolcache
         sudo rm -rf /opt/hostedtoolcache
-        echo "After removing CodeQL and other toolcaches, disk usage is:"
-        df -h
 
         # Remove .NET SDKs (frees 4.0 GB)
-        # sudo du -h -s /usr/share/dotnet
         sudo rm -rf /usr/share/dotnet
-        echo "After removing .NET SDKs, disk usage is:"
-        df -h
 
-        # # Remove Swift toolchain (frees 3GB)
-        # sudo rm -rf /usr/share/swift
-        # echo "After removing Swift toolchain, disk usage is:"
-        # df -h
-
-        # # # Remove PowerShell (frees 2GB)
-        # # sudo rm -rf /usr/local/share/powershell
-        # # echo "After removing PowerShell, disk usage is:"
-        # # df -h
-
-        # # Remove Java (JDKs) (frees 2GB)
-        # sudo rm -rf /usr/lib/jvm
-        # echo "After removing Java (JDKs), disk usage is:"
-        # df -h
-
-        # # Remove Julia (frees 1GB)
-        # sudo rm -rf /usr/local/julia*
-        # echo "After removing Julia, disk usage is:"
-        # df -h
-
-        # # Remove Chromium (frees 1GB))
-        # sudo rm -rf /usr/local/share/chromium
-        # echo "After removing Chromium, disk usage is:"
-        # df -h
-
-        # # Remove Microsoft/Edge and Google Chrome builds (frees 1GB)
-        # sudo rm -rf /opt/microsoft /opt/google
-        # echo "After removing Microsoft/Edge and Google Chrome builds, disk usage is:"
-        # df -h
-
-        # # Remove Azure CLI (frees < 1GB)
-        # sudo rm -rf /opt/az
-        # echo "After removing Azure CLI, disk usage is:"
-        # df -h
-
-        # docker system prune -af || true
-        # echo "After Docker system prune, disk usage is:"
-        # df -h
-        # docker builder prune -af || true
-        # echo "After Docker builder prune, disk usage is:"
-        # df -h
-
-    # - name: Install dependencies
+    # - name: Aggressive cleanup
     #   run: |
-    #     sudo apt update
-    #     sudo DEBIAN_FRONTEND=noninteractive apt-get -q -y install autopkgtest qemu-system qemu-utils autodep8 genisoimage python3-distro-info
+    #     echo "Before cleanup, disk usage is:"
+    #     df -h
 
-    # - name: Show disk usage
-    #   run: df -h
+    #     # Remove Android SDKs (frees 12 GB)
+    #     # sudo du -h -s /usr/local/lib/android
+    #     sudo rm -rf /usr/local/lib/android
+    #     echo "After removing Android SDKs, disk usage is:"
+    #     df -h
 
-    # - name: Build test image
-    #   run: |
-    #     cd "${GITHUB_WORKSPACE}"
-    #     echo "Building test image for $(lsb_release -c -s)"
-    #     sudo chown ${USER} /dev/kvm
-    #     autopkgtest-buildvm-ubuntu-cloud -v --release=$(lsb_release -c -s)
+    #     # Remove Haskell (GHC) (frees 6.4 GB)
+    #     # sudo du -h -s /usr/local/.ghcup
+    #     sudo rm -rf /usr/local/.ghcup
+    #     echo "After removing Haskell (GHC), disk usage is:"
+    #     df -h
 
-    # - name: Show disk usage
-    #   run: df -h
+    #     # Remove CodeQL and other toolcaches (frees 5.8 GB)
+    #     # sudo du -h -s /opt/hostedtoolcache
+    #     sudo rm -rf /opt/hostedtoolcache
+    #     echo "After removing CodeQL and other toolcaches, disk usage is:"
+    #     df -h
+
+    #     # Remove .NET SDKs (frees 4.0 GB)
+    #     # sudo du -h -s /usr/share/dotnet
+    #     sudo rm -rf /usr/share/dotnet
+    #     echo "After removing .NET SDKs, disk usage is:"
+    #     df -h
+
+    #     # # Remove Swift toolchain (frees 3GB)
+    #     # sudo rm -rf /usr/share/swift
+    #     # echo "After removing Swift toolchain, disk usage is:"
+    #     # df -h
+
+    #     # # # Remove PowerShell (frees 2GB)
+    #     # # sudo rm -rf /usr/local/share/powershell
+    #     # # echo "After removing PowerShell, disk usage is:"
+    #     # # df -h
+
+    #     # # Remove Java (JDKs) (frees 2GB)
+    #     # sudo rm -rf /usr/lib/jvm
+    #     # echo "After removing Java (JDKs), disk usage is:"
+    #     # df -h
+
+    #     # # Remove Julia (frees 1GB)
+    #     # sudo rm -rf /usr/local/julia*
+    #     # echo "After removing Julia, disk usage is:"
+    #     # df -h
+
+    #     # # Remove Chromium (frees 1GB))
+    #     # sudo rm -rf /usr/local/share/chromium
+    #     # echo "After removing Chromium, disk usage is:"
+    #     # df -h
+
+    #     # # Remove Microsoft/Edge and Google Chrome builds (frees 1GB)
+    #     # sudo rm -rf /opt/microsoft /opt/google
+    #     # echo "After removing Microsoft/Edge and Google Chrome builds, disk usage is:"
+    #     # df -h
+
+    #     # # Remove Azure CLI (frees < 1GB)
+    #     # sudo rm -rf /opt/az
+    #     # echo "After removing Azure CLI, disk usage is:"
+    #     # df -h
+
+    #     # docker system prune -af || true
+    #     # echo "After Docker system prune, disk usage is:"
+    #     # df -h
+    #     # docker builder prune -af || true
+    #     # echo "After Docker builder prune, disk usage is:"
+    #     # df -h
+
+    - name: Install dependencies
+      run: |
+        sudo apt update
+        sudo DEBIAN_FRONTEND=noninteractive apt-get -q -y install autopkgtest qemu-system qemu-utils autodep8 genisoimage python3-distro-info
+
+    - name: Show disk usage
+      run: df -h
+
+    - name: Build test image
+      run: |
+        cd "${GITHUB_WORKSPACE}"
+        echo "Building test image for $(lsb_release -c -s)"
+        sudo chown ${USER} /dev/kvm
+        autopkgtest-buildvm-ubuntu-cloud -v --release=$(lsb_release -c -s)
+
+    - name: Show disk usage
+      run: df -h
 
     # - name: Checkout
     #   uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b #v3.0.2
